Repository micronaut-projects/micronaut-data, pull requests merged in 2022-05, with the labels that each got.

#1480 [data] Update common files for branch master
  .github/dependabot.yml
Labels: relates-to: build

#1514 Fix compilation flakiness
  config/accepted-api-changes.json
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/AbstractPrefixPatternMethodMatcher.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/AbstractSpecificationMethodMatcher.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/SaveEntityMethodMatcher.java
Labels: type: bug

#1529 [data] Update common files for branch master
  .github/release.yml
  .github/renovate.json
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#1531 Fix regression with Enums not being persisted using `toString`
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2EnumsMappingSpec.groovy
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/DtoSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/mapper/QueryStatement.java
Labels: type: regression

#1533 [data] Update common files for branch master
  .github/release.yml
  .github/workflows/graalvm.yml
Labels: relates-to: build

#1553 Fix MongoDB date criteria
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/MongoQueryBuilder.java
  data-document-tck/src/main/groovy/io/micronaut/data/document/tck/AbstractDocumentRepositorySpec.groovy
  data-document-tck/src/main/java/io/micronaut/data/document/tck/entities/Book.java
  data-document-tck/src/main/java/io/micronaut/data/document/tck/entities/Person.java
  data-document-tck/src/main/java/io/micronaut/data/document/tck/repositories/PersonRepository.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/AbstractMongoRepositoryOperations.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoRepositoryOperations.java
  data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoDocumentRepositorySpec.groovy
Labels: type: bug
