Repository micronaut-projects/micronaut-data, pull requests merged in 2023-09, with the labels that each got.

#2476 Fix criteria specification issue where association identity is in the criteria
  data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/RelPersonRepository.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/entities/RelPerson.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/util/Joiner.java
  data-runtime/src/test/kotlin/io/micronaut/data/runtime/criteria/ext/KCriteriaBuilderExtKtTest.kt
Labels: type: bug

#2477 rename to persistence-api & transaction-api
  data-bom/build.gradle
  gradle/libs.versions.toml
Labels: relates-to: build

#2478 Remove version compat suppressions now 4.1.1 is released
  data-bom/build.gradle
Labels: relates-to: build

#2488 [data] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#2491 Propagate context in Hibernate Reactive
  data-hibernate-reactive/build.gradle
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/operations/ReactiveHibernateHelper.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/Foo.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/FooController.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/FooRepository.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/FooService.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/ReactiveDataSpec.groovy
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/RequestContext.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/propagate/TestClient.java
Labels: type: bug

#2498 Support underscore in repo methods to avoid mapped properties ambiguity
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/many2one/MultiManyToOneJoinSpec.groovy
  data-model/src/main/java/io/micronaut/data/model/PersistentEntityUtils.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/AbstractCriteriaMethodMatch.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/Projections.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
Labels: type: bug

#2499 [data] Update common files for branch master
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2511 [data] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2513 Fix loading entity with many to one consisting only of id field
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/many2one/MultiManyToOneJoinSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java
Labels: type: bug

#2515 use transaction-manager in lower kebap case
  data-spring-jdbc/src/test/groovy/io/micronaut/data/spring/jdbc/SpringJdbcTransactionSpec.groovy
  data-spring-jdbc/src/test/groovy/io/micronaut/data/spring/jdbc/SpringPostgresJdbcTransactionSpec.groovy
  data-spring-jpa/src/test/groovy/io/micronaut/data/spring/hibernate/H2Properties.groovy
  data-spring-jpa/src/test/groovy/io/micronaut/data/spring/hibernate/SpringHibernateTransactionSpec.groovy
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractDataSourceTransactionManagerCondition.java
  doc-examples/hibernate-spring-tx-example-java/src/test/java/example/BookRepositorySpec.java
  doc-examples/jdbc-spring-tx-example-java/src/test/java/example/BookRepositorySpec.java
Labels: type: improvement

#2494 Document how to use Spring JdbcTemplate, with multi-language examples.
  doc-examples/jdbc-spring-template-example-groovy/build.gradle
  doc-examples/jdbc-spring-template-example-groovy/gradle.properties
  doc-examples/jdbc-spring-template-example-groovy/src/main/groovy/example/AbstractBookRepository.groovy
  doc-examples/jdbc-spring-template-example-groovy/src/main/groovy/example/Book.groovy
  doc-examples/jdbc-spring-template-example-groovy/src/main/resources/application.yml
  doc-examples/jdbc-spring-template-example-groovy/src/main/resources/logback.xml
  doc-examples/jdbc-spring-template-example-groovy/src/test/groovy/example/BookRepositorySpec.groovy
  doc-examples/jdbc-spring-template-example-java/build.gradle
  doc-examples/jdbc-spring-template-example-java/gradle.properties
  doc-examples/jdbc-spring-template-example-java/src/main/java/example/AbstractBookRepository.java
  doc-examples/jdbc-spring-template-example-java/src/main/java/example/Book.java
  doc-examples/jdbc-spring-template-example-java/src/main/resources/application.yml
  doc-examples/jdbc-spring-template-example-java/src/main/resources/logback.xml
  doc-examples/jdbc-spring-template-example-java/src/test/java/example/BookRepositoryTest.java
  doc-examples/jdbc-spring-template-example-kotlin/build.gradle
  doc-examples/jdbc-spring-template-example-kotlin/gradle.properties
  doc-examples/jdbc-spring-template-example-kotlin/src/main/kotlin/example/AbstractBookRepository.kt
  doc-examples/jdbc-spring-template-example-kotlin/src/main/kotlin/example/Book.kt
  doc-examples/jdbc-spring-template-example-kotlin/src/main/resources/application.yml
  doc-examples/jdbc-spring-template-example-kotlin/src/main/resources/logback.xml
  doc-examples/jdbc-spring-template-example-kotlin/src/test/kotlin/example/BookRepositoryTest.kt
  settings.gradle
  src/main/docs/guide/dbc/dbcRepositories.adoc
Labels: type: docs

#2520 bug: JPA if native use createNativeMutationQuery
  data-hibernate-jpa/build.gradle
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/nativepostgresql/Product.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/nativepostgresql/ProductRepository.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/nativepostgresql/ProductRepositoryTest.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/nativepostgresql/SqlUtils.java
  data-hibernate-jpa/src/test/resources/sql/seed-data.sql
Labels: type: bug

#2523 MongoDB: Support `arrayFilters`
  data-document-processor/src/main/java/io/micronaut/data/document/processor/matchers/MongoRawQueryMethodMatcher.java
  data-document-tck/src/main/java/io/micronaut/data/document/tck/entities/Person.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/annotation/MongoUpdateOptions.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/annotation/MongoUpdateQuery.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/options/MongoOptionsUtils.java
  data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoDocumentRepositorySpec.groovy
  data-mongodb/src/test/java/io/micronaut/data/document/mongodb/repositories/MongoPersonRepository.java
Labels: type: improvement

#2529 Use schema for many to many join table creation, select and insert
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/many2many/ManyToManyJoinTableSpec.groovy
  data-model/src/main/java/io/micronaut/data/annotation/sql/JoinTable.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildTableSpec.groovy
Labels: type: bug

#2532 Support custom save method with non generated id
  data-jdbc/src/test/resources/application-oracle-jsonview.yml
  data-r2dbc/src/test/resources/application-oracle-jsonview.yaml
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractJSONSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/JsonEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/JsonEntityRepository.java
Labels: type: bug

#2534 [data] Update common files for branch master
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#2527 R2DBC Correct canceling a transaction
  data-connection/src/main/java/io/micronaut/data/connection/reactive/DefaultReactiveConnectionStatus.java
  data-connection/src/main/java/io/micronaut/data/connection/reactive/ReactiveConnectionStatus.java
  data-connection/src/main/java/io/micronaut/data/connection/reactive/ReactiveConnectionSynchronization.java
  data-connection/src/main/java/io/micronaut/data/connection/support/AbstractReactorConnectionOperations.java
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/PlainR2dbcSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/mariadb/MariaDbPlainR2dbcSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/mysql/MySqlDbPlainR2dbcSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/oraclexe/OracleXEPlainR2dbcSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/postgres/PostgresPlainR2dbcSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/sqlserver/SqlServerPlainR2dbcSpec.groovy
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractReactorTransactionOperations.java
  data-tx/src/main/java/io/micronaut/transaction/support/SyncCompleteAndErrorPublisher.java
  data-tx/src/test/java/io/micronaut/transaction/OpLogger.java
  data-tx/src/test/java/io/micronaut/transaction/ReactiveConnManager.java
  data-tx/src/test/java/io/micronaut/transaction/ReactiveTxManager.java
  data-tx/src/test/java/io/micronaut/transaction/TxExample.java
  data-tx/src/test/java/io/micronaut/transaction/TxSpec.java
  doc-examples/azure-cosmos-example-kotlin/src/main/resources/logback.xml
  doc-examples/mongo-reactive-example-kotlin/src/main/resources/logback.xml
Labels: type: bug

#2535 Fix embedded id naming issue when using QueryModel directly
  data-model/src/main/java/io/micronaut/data/model/naming/NamingStrategy.java
  data-model/src/main/java/io/micronaut/data/model/runtime/RuntimePersistentProperty.java
  data-processor/build.gradle
  data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/java/io/micronaut/data/processor/entity/ActivityPeriodEntity.java
  data-processor/src/test/java/io/micronaut/data/processor/entity/ActivityPeriodPersonEntity.java
  data-processor/src/test/java/io/micronaut/data/processor/entity/ActivityPeriodPersonId.java
  data-processor/src/test/java/io/micronaut/data/processor/entity/ActivityPersonEntity.java
  data-processor/src/test/java/io/micronaut/data/processor/entity/package-info.java
Labels: type: bug

#2536 Support coroutine connection and transaction operations
  data-connection/build.gradle
  data-connection/src/main/java/io/micronaut/data/connection/support/AbstractReactorConnectionOperations.java
  data-connection/src/main/kotlin/io/micronaut/data/connection/kotlin/CoroutineConnectionOperations.kt
  data-connection/src/main/kotlin/io/micronaut/data/connection/kotlin/DefaultCoroutineConnectionOperations.kt
  data-runtime/src/main/kotlin/io/micronaut/data/runtime/reactive/MicronautContextInjector.kt
  data-runtime/src/main/resources/META-INF/services/kotlinx.coroutines.reactive.ContextInjector
  data-tx/build.gradle
  data-tx/src/main/kotlin/io/micronaut/transaction/kotlin/CoroutineTransactionOperations.kt
  data-tx/src/main/kotlin/io/micronaut/transaction/kotlin/CoroutineTransactionStatus.kt
  data-tx/src/main/kotlin/io/micronaut/transaction/kotlin/DefaultCoroutineTransactionOperations.kt
  data-tx/src/main/kotlin/io/micronaut/transaction/kotlin/DefaultCoroutineTransactionStatus.kt
  doc-examples/mongo-reactive-example-kotlin/build.gradle
  doc-examples/mongo-reactive-example-kotlin/src/main/kotlin/example/PersonSuspendRepositoryService.kt
  doc-examples/r2dbc-example-kotlin/src/test/kotlin/example/TxTest3.kt
  src/main/docs/guide/shared/transactions/programmaticTransactions.adoc
Labels: type: improvement
