Repository micronaut-projects/micronaut-data, pull requests merged in 2023-08, with the labels that each got.

#2424 Revert sede upgrade
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2425 Remove unnecessary version numbers from docs.
  src/main/docs/guide/dbc/jdbc/jdbcQuickStart.adoc
  src/main/docs/guide/dbc/sqlMapping.adoc
  src/main/docs/guide/spring.adoc
Labels: type: docs

#2430 [data] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#2437 [data] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#2444 Support NESTED transaction propagation
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/AbstractJdbcTransactionSpec.groovy
  data-spring-jdbc/src/main/java/io/micronaut/data/spring/tx/AbstractSpringTransactionOperations.java
  data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/hibernate/SpringHibernateTransactionOperations.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractTransactionSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/services/TxBookService.java
  data-tx-hibernate/src/main/java/io/micronaut/transaction/hibernate/HibernateTransactionManager.java
  data-tx-hibernate/src/test/groovy/io/micronaut/transaction/hibernate6/HibernateTransactionSpec.groovy
  data-tx-jdbc/src/main/java/io/micronaut/transaction/jdbc/DataSourceTransactionManager.java
  data-tx/src/main/java/io/micronaut/transaction/impl/AbstractInternalTransaction.java
  data-tx/src/main/java/io/micronaut/transaction/impl/DefaultTransactionStatus.java
  data-tx/src/main/java/io/micronaut/transaction/impl/InternalTransaction.java
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractTransactionOperations.java
Labels: type: improvement

#2467 Don't create join table when there is join column configured on foreign key
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/one2many/OneToManyJoinColumnSpec.groovy
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildTableSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/RelationshipSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/jdbc/entities/Employee.java
  data-tck/src/main/java/io/micronaut/data/tck/jdbc/entities/EmployeeGroup.java
Labels: type: bug

#2469 Use JoinColumn column when specified vs association id
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/many2one/MultiManyToOneJoinSpec.groovy
  data-model/src/main/java/io/micronaut/data/model/PersistentEntityUtils.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/MappedEntityVisitor.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
Labels: type: bug

#2471 [data] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build
