Repository micronaut-projects/micronaut-data, pull requests merged in 2023-10, with the labels that each got.

#2550 Fix JPA sort issue for embedded field
  data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/UserWithWhereRepository.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/entities/Audit.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/entities/UserWithWhere.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java
Labels: type: bug

#2557 [data] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#2581 Fix documentation example as batch update cannot return list of results
  data-document-processor/src/test/groovy/io/micronaut/data/document/processor/BuildMongoQuerySpec.groovy
  doc-examples/mongo-example-groovy/src/main/groovy/example/BookRepository.groovy
  doc-examples/mongo-example-java/src/main/java/example/BookRepository.java
  doc-examples/mongo-example-kotlin-ksp/src/main/kotlin/example/BookRepository.kt
  doc-examples/mongo-example-kotlin/src/main/kotlin/example/BookRepository.kt
  doc-examples/mongo-example-records-java/src/main/java/example/BookRepository.java
Labels: type: docs
