Repository micronaut-projects/micronaut-data, pull requests merged in 2023-07, with the labels that each got.

#2324 [data] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#2347 [data] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2366 Data no milestone
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2361 Improve docs
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/whatsNew.adoc
Labels: type: docs

#2395 Make supported naming strategies available at runtime for native image
  data-model/src/main/java/io/micronaut/data/model/AbstractPersistentEntity.java
  data-model/src/main/java/io/micronaut/data/model/naming/NamingStrategies.java
  doc-examples/jdbc-example-java/src/main/java/example/User.java
  doc-examples/jdbc-example-java/src/main/java/example/UserRepository.java
  doc-examples/jdbc-example-java/src/test/java/example/UserRepositorySpec.java
  src/main/docs/guide/dbc/sqlMapping/sqlNaming.adoc
Labels: type: bug

#2400 [data] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2405 Fix lessThanOrEqual in Kotlin criteria builder
  data-runtime/src/main/kotlin/io/micronaut/data/runtime/criteria/KCriteriaBuilderExt.kt
  data-runtime/src/test/kotlin/io/micronaut/data/runtime/criteria/ext/KCriteriaBuilderExtKtTest.kt
Labels: type: bug

#2383 Fix for reading results for left join one to many collections
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/one2many/DoubleOneToManyJoinSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java
Labels: type: bug

#2408 [data] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#2413 Support like criteria for MongoDB
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/MongoQueryBuilder.java
  data-document-tck/src/main/groovy/io/micronaut/data/document/tck/AbstractDocumentRepositorySpec.groovy
  data-document-tck/src/main/java/io/micronaut/data/document/tck/repositories/PersonRepository.java
Labels: type: improvement

#2414 Fix dynamic order by fields in EmbeddedId
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2EmbeddedIdSpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/ShipmentRepository.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java
Labels: type: bug

#2417 [data] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build
