Repository micronaut-projects/micronaut-data, pull requests merged in 2024-01, with the labels that each got.

#2713 [data] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#2728 Fix NamingStrategies javadoc and add note for hibernate join collection tests
  data-model/src/main/java/io/micronaut/data/model/naming/NamingStrategies.java
  src/main/docs/guide/hibernate/hibernateJoinQueries.adoc
Labels: type: docs

#2735 Handle null Specification parameter in repository methods
  data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy
  data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/JpaSpecificationCrudRepositorySpec.groovy
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/repository/jpa/intercept/AbstractSpecificationInterceptor.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/repository/jpa/intercept/ReactiveCountSpecificationInterceptor.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/repository/jpa/intercept/ReactiveFindAllSpecificationInterceptor.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/repository/jpa/intercept/ReactiveFindOneSpecificationInterceptor.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/repository/jpa/intercept/ReactiveFindPageSpecificationInterceptor.java
  data-hibernate-reactive/src/test/groovy/io/micronaut/data/hibernate/reactive/JpaSpecificationCrudRepositorySpec.groovy
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/AbstractSpecificationInterceptor.java
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/CountSpecificationInterceptor.java
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/DeleteSpecificationInterceptor.java
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/FindAllSpecificationInterceptor.java
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/FindOneSpecificationInterceptor.java
  data-jpa/src/main/java/io/micronaut/data/jpa/repository/intercept/FindPageSpecificationInterceptor.java
  data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/intercept/CountSpecificationInterceptor.java
  data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/intercept/DeleteSpecificationInterceptor.java
  data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/intercept/FindAllSpecificationInterceptor.java
  data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/intercept/FindOneSpecificationInterceptor.java
  data-spring-jpa/src/test/groovy/io/micronaut/data/spring/hibernate/SpringCrudRepositoryNullSpecJpaSpec.groovy
Labels: type: bug

#2741 Fix parameter binding for countBy queries
  data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultStoredQuery.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/BookRepository.java
Labels: type: bug
