Repository micronaut-projects/micronaut-data, pull requests merged in 2024-07, with the labels that each got.

#2998 [data] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  config/checkstyle/custom-suppressions.xml
  config/checkstyle/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#2986 [data] Update common files for branch 4.8.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#3007 CursoredPage not supported with findAll and PredicateSpecification
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2CursoredPaginationSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/mysql/MysqlCursoredPaginationSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/OracleXECursoredPaginationSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresCursoredPaginationSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/sqlserver/SqlServerCursoredPaginationSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/h2/H2CursoredPaginationSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/mysql/MySqlCursoredPaginationSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/oraclexe/OracleXECursoredPaginationSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/postgres/PostgresCursoredPaginationSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/AbstractSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/FindPageSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/reactive/AbstractReactiveSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/reactive/FindPageReactiveSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultFindPageReactiveInterceptor.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractCursoredPageSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractReactiveRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/PersonReactiveRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/PersonRepository.java
Labels: type: improvement

#3025 Fix for cascade save operation with one-to-many relations
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2CascadeSpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/CascadeEntity.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/CascadeEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/CascadeSubEntityA.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/CascadeSubEntityB.java
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractSyncEntitiesOperations.java
Labels: type: bug

#3031 [data] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
