Repository micronaut-projects/micronaut-data, pull requests merged in 2024-05, with the labels that each got.

#2912 Fix issue with building the CriteriaSort properly
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/AbstractSpecificationInterceptor.java
  doc-examples/hibernate-example-kotlin/src/main/kotlin/example/Child.kt
  doc-examples/hibernate-example-kotlin/src/test/kotlin/example/HibernateTxTest.kt
Labels: type: bug

#2946 Additional example docs for programmatic transactions and repositories
  doc-examples/jdbc-example-groovy/src/main/groovy/example/ProductManager.groovy
  doc-examples/jdbc-example-groovy/src/main/groovy/example/ProductRepository.groovy
  doc-examples/jdbc-example-groovy/src/test/groovy/example/ProductManagerSpec.groovy
  doc-examples/jdbc-example-java/src/main/java/example/ProductManager.java
  doc-examples/jdbc-example-java/src/main/java/example/ProductRepository.java
  doc-examples/jdbc-example-java/src/test/java/example/ProductManagerSpec.java
  doc-examples/jdbc-example-kotlin/src/main/kotlin/example/ProductManager.kt
  doc-examples/jdbc-example-kotlin/src/main/kotlin/example/ProductRepository.kt
  doc-examples/jdbc-example-kotlin/src/test/kotlin/example/ProductManagerSpec.kt
  src/main/docs/guide/shared/transactions/programmaticTransactions.adoc
Labels: type: docs

#2954 Transaction manager should catch `Throwable`
  data-tx/src/main/java/io/micronaut/transaction/async/AsyncUsingSyncTransactionOperations.java
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractTransactionOperations.java
  doc-examples/jdbc-example-kotlin/src/main/kotlin/example/PersonSuspendRepositoryService.kt
  doc-examples/jdbc-example-kotlin/src/test/kotlin/example/TxTest.kt
Labels: type: bug

#2931 [data] Update common files for branch 4.8.x
  .github/workflows/gradle.yml
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#1789 Add support for sequence type for h2
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java
  data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildInsertSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildTableSpec.groovy
Labels: type: enhancement

#2961 [data] Update common files for branch 4.8.x
  .github/workflows/gradle.yml
Labels: relates-to: build
