Repository micronaut-projects/micronaut-data, pull requests merged in 2024-08, with the labels that each got.

#3047 Fix nested transaction savepoint handling in JDBC transaction manager
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/mariadb/MariaTransactionsSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/mysql/MySqlTransactionsSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/OracleTransactionsSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresTransactionsSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/sqlserver/SqlServerTransactionsSpec.groovy
  data-spring-jdbc/src/test/groovy/io/micronaut/data/spring/jdbc/SpringPostgresJdbcTransactionSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractTransactionSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/services/TxBookService.java
  data-tx-hibernate/build.gradle
  data-tx-hibernate/src/main/java/io/micronaut/transaction/hibernate/HibernateTransactionManager.java
  data-tx-hibernate/src/test/groovy/io/micronaut/transaction/hibernate6/HibernateTransactionSpec.groovy
  data-tx-hibernate/src/test/groovy/io/micronaut/transaction/hibernate6/OracleHibernateTransactionSpec.groovy
  data-tx-hibernate/src/test/groovy/io/micronaut/transaction/hibernate6/SqlServerHibernateTransactionSpec.groovy
  data-tx-jdbc/src/main/java/io/micronaut/transaction/jdbc/DataSourceTransactionManager.java
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractDefaultTransactionOperations.java
Labels: type: bug

#3055 doc. add link to GitHub repository
  src/main/docs/guide/repository.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#3057 Fix query with predication specification and cursored pageable
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/FindPageSpecificationInterceptor.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractCursoredPageSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/PersonRepository.java
Labels: type: bug

#3051 [data] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#3053 Fix pageable query with join criteria
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/PageSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/AuthorRepository.java
Labels: type: bug

#3065 [data] Update common files for branch 4.9.x
  .github/workflows/release.yml
Labels: relates-to: build

#3094 Support like predicate in custom query builders
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/query/QueryModelPredicateVisitor.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/java/io/micronaut/data/annotation/custom/CustomRepository.java
  data-processor/src/test/java/io/micronaut/data/query/builder/custom/CustomQueryBuilder.java
Labels: type: bug
