Repository micronaut-projects/micronaut-data, pull requests merged in 2024-09, with the labels that each got.

#3090 Change AbstractQueryInterceptor.getParameterInRole to be protected and reusable
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java
Labels: type: improvement

#3097 fix: Defer R2DBC Transactional callbacks using flatMap
  data-tx/src/main/java/io/micronaut/transaction/support/AbstractReactorTransactionOperations.java
  doc-examples/r2dbc-micrometer-example-java/build.gradle
  doc-examples/r2dbc-micrometer-example-java/gradle.properties
  doc-examples/r2dbc-micrometer-example-java/src/main/java/com/example/Application.java
  doc-examples/r2dbc-micrometer-example-java/src/main/java/com/example/MyService.java
  doc-examples/r2dbc-micrometer-example-java/src/main/java/com/example/SimpleController.java
  doc-examples/r2dbc-micrometer-example-java/src/main/resources/application.properties
  doc-examples/r2dbc-micrometer-example-java/src/main/resources/logback.xml
  doc-examples/r2dbc-micrometer-example-java/src/test/java/com/example/R2dbcAndMicrometerTest.java
  settings.gradle
Labels: type: bug

#3100 Next phase criteria refactoring to allow more complex scenarios
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/CosmosSqlQueryBuilder2.java
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/MongoQueryBuilder2.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2RepositorySpec.groovy
  data-model/src/main/java/io/micronaut/data/model/PersistentPropertyPath.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/ExpressionType.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/IExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/IPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentPropertyPath.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractCriteriaBuilder.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityCriteriaQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityJoinSupport.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/CriteriaUtils.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/DefaultParameterExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/DefaultPersistentPropertyPath.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/ParameterExpressionImpl.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/PredicateVisitor.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/AbstractExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/BinaryExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/ClassExpressionType.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/FunctionExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/IdExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/LiteralExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/UnaryExpression.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/UnaryExpressionType.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/BetweenPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/BinaryPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/InPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/LikePredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/PersistentPropertyUnaryPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/PredicateBinaryOp.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/PredicateUnaryOp.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/UnaryPredicate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/query/QueryModelPredicateVisitor.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/util/Joiner.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/impl/AdvancedPredicateVisitor.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/ClassElementExpressionType.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/QueryResultAnalyzer.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourceParameterExpressionImpl.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentAssociationPath.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentEntityPath.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentEntityRoot.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentPropertyPath.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/Projections.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/TypeUtils.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/DeleteCriteriaMethodMatch.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/UpdateCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/model/jpa/criteria/CriteriaSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/criteria/RuntimePersistentEntityRoot.java
  data-runtime/src/test/groovy/io/micronaut/data/runtime/criteria/CriteriaSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractCriteriaSpec.groovy
Labels: type: improvement

#3106 Fix mongo custom query pagination
  data-model/src/main/java/io/micronaut/data/model/Pageable.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoRepositoryOperations.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java
  data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoDocumentRepositorySpec.groovy
  data-mongodb/src/test/java/io/micronaut/data/document/mongodb/repositories/MongoPersonRepository.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/DefaultStoredQueryResolver.java
Labels: type: bug

#3109 [data] Update common files for branch 4.10.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#3111 Properly handle transaction commit errors
  data-tx/src/main/java/io/micronaut/transaction/async/AsyncUsingReactiveTransactionOperations.java
  data-tx/src/main/java/io/micronaut/transaction/async/AsyncUsingSyncTransactionOperations.java
Labels: type: bug

#3120 Refactor limit, offset
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/CosmosSqlQueryBuilder2.java
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/MongoQueryBuilder.java
  data-document-model/src/main/java/io/micronaut/data/document/model/query/builder/MongoQueryBuilder2.java
  data-document-processor/src/main/java/io/micronaut/data/document/processor/matchers/MongoRawQueryMethodMatcher.java
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/operations/DefaultHibernateReactiveRepositoryOperations.java
  data-model/src/main/java/io/micronaut/data/intercept/annotation/DataMethod.java
  data-model/src/main/java/io/micronaut/data/model/Pageable.java
  data-model/src/main/java/io/micronaut/data/model/Sort.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/expression/SubqueryExpression.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/QueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/QueryResult.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/jpa/JpaQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/MethodMatchSourcePersistentEntityCriteriaBuilderImpl.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/QueryResultAnalyzer.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentEntityCriteriaQueryImpl.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/FindSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/JpaOrderBySpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/AbstractSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/reactive/AbstractReactiveSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/DefaultSqlPreparedQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultStoredQuery.java
Labels: type: improvement

#3130 MongoDB: Ignore basic types codecs
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java
  data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoRuntimeSpec.groovy
Labels: type: bug

#3136 Improved Criteria docs
  data-connection-jdbc/build.gradle
  data-jdbc/src/test/resources/application.yml
  data-model/src/main/java/io/micronaut/data/repository/jpa/criteria/SpecificationComposition.java
  data-r2dbc/src/test/resources/application.yaml
  data-tx-hibernate/src/test/groovy/io/micronaut/transaction/hibernate6/SqlServerHibernateTransactionSpec.groovy
  src/main/docs/guide/dbc/dbcCriteriaSpecifications.adoc
  src/main/docs/guide/dbc/dbcCriteriaSpecifications/otherRepositoryVariations.adoc
  src/main/docs/guide/hibernate/hibernateSpecifications.adoc
  src/main/docs/guide/mongo/mongoCriteriaSpecifications/mongoOtherRepositoryVariations.adoc
  src/main/docs/guide/shared.adoc
  src/main/docs/guide/shared/criteriaSpecifications.adoc
  src/main/docs/guide/shared/criteriaSpecifications/criteriaExecuteDelete.adoc
  src/main/docs/guide/shared/criteriaSpecifications/criteriaExecuteQuery.adoc
  src/main/docs/guide/shared/criteriaSpecifications/criteriaExecuteUpdate.adoc
  src/main/docs/guide/shared/criteriaSpecifications/otherRepositoryVariations.adoc
  src/main/docs/guide/shared/criteriaSpecifications/typeSafeJava.adoc
  src/main/docs/guide/toc.yml
Labels: type: improvement

#3142 Fix serialization of Page.empty()
  data-model/src/main/java/io/micronaut/data/model/DefaultPage.java
  data-model/src/main/java/io/micronaut/data/model/Page.java
  data-model/src/test/groovy/io/micronaut/data/model/PageSpec.groovy
Labels: type: bug

#3145 Fix converter on many-to-many table
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/Course.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/CourseRepository.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/ManyToManyAttributeSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/Student.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/StudentId.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/StudentRepository.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/AbstractSqlRepositoryOperations.java
Labels: type: bug

#3152 Refactoring for paginated JOIN support
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/operations/DefaultHibernateReactiveRepositoryOperations.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2RepositorySpec.groovy
  data-model/src/main/java/io/micronaut/data/intercept/annotation/DataMethod.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntityCommonAbstractCriteria.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntityCriteriaQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntityQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntityRoot.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntitySubquery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityCriteriaDelete.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityCriteriaQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityCriteriaUpdate.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityQuery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntitySubquery.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/QueryResultPersistentEntityCriteriaQuery.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/QueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/QueryParameterBinding.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/jpa/JpaQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentEntityCriteriaQueryImpl.java
  data-processor/src/main/java/io/micronaut/data/processor/model/criteria/impl/SourcePersistentEntitySubqueryImpl.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/MatchContext.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/AbstractCriteriaMethodMatch.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/CountMethodMatcher.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/FindMethodMatcher.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/UpdateCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/FindSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/criteria/RuntimePersistentEntityCriteriaQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/criteria/RuntimePersistentEntitySubquery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultCountInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultDeleteAllInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultExistsByInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultFindOneInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultProcedureReturningManyInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultProcedureReturningOneInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/DefaultUpdateInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultCountAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultDeleteAllAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultExistsByAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultProcedureReturningManyAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultProcedureReturningOneAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/async/DefaultUpdateAsyncInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/AbstractSpecificationInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultCountReactiveInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultDeleteAllReactiveInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultExistsByReactiveInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultProcedureReactiveInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/reactive/DefaultUpdateReactiveInterceptor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/query/DefaultBindableParametersStoredQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/DefaultSqlPreparedQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/DefaultStoredQueryResolver.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/StoredQueryResolver.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultStoredQuery.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/BookRepository.java
Labels: type: improvement
