Repository micronaut-projects/micronaut-data, pull requests merged in 2024-11, with the labels that each got.

#3182 [data] Update common files for branch 4.10.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#3217 Fix operation type of count
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
Labels: type: bug

#3122 Get ready for strict image heap
  buildSrc/src/main/groovy/io.micronaut.build.internal.data-native-example.gradle
  data-model/src/main/resources/META-INF/native-image/io.micronaut.data/data-model/native-image.properties
  data-mongodb/src/main/resources/META-INF/native-image/io.micronaut.data/micronaut-data-mongodb/native-image.properties
  gradle/libs.versions.toml
Labels: relates-to: graal

#3223 Fix mapping with embedded field with generic type
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2RepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2BookEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2HouseEntityRepository.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BaseEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BookEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BookState.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/HouseEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/HouseState.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/ResourceEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/StateConverter.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/embedded/BookEntityRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/embedded/HouseEntityRepository.java
Labels: type: bug

#3222 Oracle duality Json View optimization in property comparison and sort
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/OracleJdbcJsonViewSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/Student.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/StudentView.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/StudentViewRepository.java
  data-jdbc/src/test/resources/oracle-jsonview-migrations/V1__Create_Schema.sql
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/JsonViewSpec.groovy
Labels: type: improvement

#3224 Fix mapping with embedded field with generic type
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2RepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2BookEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2HouseEntityRepository.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BaseEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BookEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/BookState.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/HouseEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/HouseState.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/ResourceEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/embedded/StateConverter.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/embedded/BookEntityRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/embedded/HouseEntityRepository.java
Labels: type: bug

#3227 Enhance "RETURNING" clause method matching
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/RawQueryMethodMatcher.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildDeleteSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildUpdateSpec.groovy
Labels: type: bug
