Repository micronaut-projects/micronaut-data, pull requests merged in 2024-10, with the labels that each got.

#3156 Hibernate: Set the order using the Hibernate API instead of modifying the query
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java
  data-hibernate-reactive/src/main/java/io/micronaut/data/hibernate/reactive/operations/DefaultHibernateReactiveRepositoryOperations.java
  data-model/src/main/java/io/micronaut/data/model/Pageable.java
Labels: type: improvement

#3159 [data] Update common files for branch 4.10.x
  .github/workflows/release.yml
  doc-examples/coherence-example-java/src/test/java/io/micronaut/coherence/data/GeneratedAsyncStatementsTest.java
Labels: relates-to: build

#3168 Use ByteArrayCodec for byte array
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/CodecUtils.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java
  data-mongodb/src/test/groovy/io/micronaut/data/document/mongodb/MongoRuntimeSpec.groovy
Labels: type: regression

#3173 Fix pageable deserialization to properly read page number
  data-model/src/main/java/io/micronaut/data/model/Pageable.java
  data-model/src/test/groovy/io/micronaut/data/model/PageSpec.groovy
Labels: type: bug

#3180 Fix mapping empty page
  data-model/src/main/java/io/micronaut/data/model/CursoredPage.java
  data-model/src/main/java/io/micronaut/data/model/Page.java
  data-model/src/test/groovy/io/micronaut/data/model/PageSpec.groovy
  src/main/docs/guide/azureCosmos/azureCosmosCriteriaSpecifications.adoc
Labels: type: bug

#3192 Fix query failing when criteriaBuilder.conjunction() is used
  .github/workflows/gradle.yml
  data-model/src/main/java/io/micronaut/data/model/CursoredPage.java
  data-model/src/main/java/io/micronaut/data/model/Page.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityCriteriaQuery.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-model/src/test/groovy/io/micronaut/data/model/PageSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/BookSpecifications.java
Labels: type: bug
