Repository micronaut-projects/micronaut-data, pull requests merged in 2024-04, with the labels that each got.

#2817 Diamonds
  data-azure-cosmos/src/main/java/io/micronaut/data/cosmos/operations/DefaultReactiveCosmosRepositoryOperations.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/AuditCompanyListener.java
  data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java
  data-model/src/main/java/io/micronaut/data/model/PersistentEntity.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractCriteriaBuilder.java
  data-model/src/main/java/io/micronaut/data/model/query/QueryModel.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/init/MongoCollectionsCreator.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/init/MongoReactiveCollectionsCreator.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoRepositoryOperations.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultReactiveMongoRepositoryOperations.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataSerdeRegistry.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/MappedEntityVisitor.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
  data-runtime/src/main/java/io/micronaut/data/runtime/criteria/RuntimePersistentEntityCriteriaQuery.java
  data-runtime/src/main/java/io/micronaut/data/runtime/support/DefaultRuntimeEntityRegistry.java
  data-spring/src/main/java/io/micronaut/data/spring/runtime/PageDelegate.java
  data-tx/src/main/java/io/micronaut/transaction/support/SyncCompleteAndErrorPublisher.java
Labels: type: improvement

#2816 Migrate to switch statements
  data-azure-cosmos/src/main/java/io/micronaut/data/cosmos/operations/DefaultReactiveCosmosRepositoryOperations.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/PredicateBinaryOp.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/predicate/PredicateUnaryOp.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/query/QueryModelPredicateVisitor.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/spec/FindAllSpecificationMethodMatcher.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/config/R2dbcSchemaGenerator.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/mapper/ColumnIndexR2dbcResultReader.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/mapper/R2dbcQueryStatement.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcSchemaHandler.java
  data-runtime/src/main/java/io/micronaut/data/runtime/mapper/ResultReader.java
Labels: type: improvement

#2818 Remove redundant cast
  data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/event/EventIntegrator.java
  data-hibernate-jpa/src/test/java/io/micronaut/data/hibernate/AuditCompanyListener.java
  doc-examples/azure-cosmos-example-groovy/src/test/groovy/example/BookRepositorySpec.groovy
  doc-examples/jooq-r2dbc-postgres/src/main/java/example/Pet.java
  doc-examples/jooq-r2dbc-postgres/src/main/java/example/PetRepository.java
Labels: type: improvement

#2853 doc: mention the validation requirement for auto-timestamps
  src/main/docs/guide/shared/dataUpdates/timestamps.adoc
Labels: type: docs

#2814 Remove redundant throws
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
  data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataSerdeRegistry.java
  data-tx/src/main/java/io/micronaut/transaction/reactive/ReactiveTransactionOperations.java
  doc-examples/hibernate-example-java/src/test/java/example/ProductRepositorySpec.java
  doc-examples/mongo-example-java/src/test/java/example/ProductRepositorySpec.java
  doc-examples/mongo-example-records-java/src/test/java/example/ProductRepositorySpec.java
  doc-examples/r2dbc-multitenancy-datasource-example-java/src/test/java/example/BookR2dbcDatasourceMultiTenancySpec.java
  doc-examples/r2dbc-multitenancy-schema-example-java/src/test/java/example/BookR2dbcSchemaMultiTenancySpec.java
Labels: type: improvement

#2867 Update versions
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2852 add explicit handling of JDBC type for Oracle boolean type
  data-jdbc/src/main/java/io/micronaut/data/jdbc/mapper/JdbcQueryStatement.java
  data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/bool/BooleanTest.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/bool/OracleBooleanTestRepository.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/bool/OracleXEBooleanTypeSpec.groovy
Labels: type: bug

#2904 split multitenancy docs
  src/main/docs/guide/multitenancy.adoc
  src/main/docs/guide/shared/multitenancy/datasourcemode.adoc
  src/main/docs/guide/shared/multitenancy/discriminatormode.adoc
  src/main/docs/guide/shared/multitenancy/schemamode.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#2910 docs: clarify how to add annotation processor dependencies for Kotlin and Groovy projects.
  data-model/src/main/java/io/micronaut/data/model/runtime/QueryParameterBinding.java
  src/main/docs/guide/azureCosmos/azureCosmosQuickStart.adoc
  src/main/docs/guide/buildConfig.adoc
  src/main/docs/guide/dbc/dbcCriteriaSpecifications/typeSafeJava.adoc
  src/main/docs/guide/dbc/jdbc/jdbcQuickStart.adoc
  src/main/docs/guide/mongo/mongoQuickStart.adoc
Labels: type: docs

#2915 Minor Improvement for Oracle JsonView optimistic locking
  data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java
  data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/OracleSqlExceptionMapper.java
  data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/SqlExceptionMapper.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/OracleJdbcJsonViewSpec.groovy
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcRepositoryOperations.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/OracleR2dbcExceptionMapper.java
  data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/R2dbcExceptionMapper.java
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/oraclexe/jsonview/OracleR2DbcJsonViewSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/AbstractSqlRepositoryOperations.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
Labels: type: improvement

#2917 Show repository with current
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/multitenancy/TenancyBook.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/multitenancy/TenancyBookController.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/multitenancy/TenancyBookControllerSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/multitenancy/TenancyBookRepository.java
  src/main/docs/guide/shared/multitenancy/discriminatormode.adoc
  src/main/docs/guide/shared/multitenancy/discriminatormode/multitenancyannotations.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#2909 docs: note that TransactionalEventListener annotation is not supported for reactive transactions
  src/main/docs/guide/shared/transactions/transactionalEvents.adoc
Labels: type: docs

#2925 Restore missing image by cherry picking from gh-pages/latest.
  src/main/docs/resources/img/finderpattern.eps
  src/main/docs/resources/img/finderpattern.png
  src/main/docs/resources/img/finderpattern.svg
Labels: type: docs
