Repository micronaut-projects/micronaut-data, pull requests merged in 2025-01, with the labels that each got.

#3230 sonatype oss Gradle plugin
  .github/renovate.json
  .github/workflows/gradle.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.data-module.gradle
  gradle/libs.versions.toml
  gradlew
Labels: relates-to: build

#3263 Fix QuerySpecification doesn't support selecting non-lowercase columns
  data-jdbc/src/main/java/io/micronaut/data/jdbc/mapper/ColumnNameExistenceAwareResultSetReader.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/H2RepositorySpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/mariadb/MariaRepositorySpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/mysql/MySqlRepositorySpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/OracleXERepositorySpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresRepositorySpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/sqlserver/SqlServerRepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2ExampleEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/mysql/MySqlExampleEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/oraclexe/OracleExampleEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/postgres/PostgresExampleEntityRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/sqlserver/MSExampleEntityRepository.java
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/h2/H2RepositorySpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/mariadb/MariaDbRepositorySpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/mysql/MySqlRepositorySpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/oraclexe/OracleXERepositorySpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/postgres/PostgresRepositorySpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/sqlserver/SqlServerRepositorySpec.groovy
  data-r2dbc/src/test/java/io/micronaut/data/r2dbc/h2/H2ExampleEntityRepository.java
  data-r2dbc/src/test/java/io/micronaut/data/r2dbc/mysql/MySqlExampleEntityRepository.java
  data-r2dbc/src/test/java/io/micronaut/data/r2dbc/oraclexe/OracleExampleEntityRepository.java
  data-r2dbc/src/test/java/io/micronaut/data/r2dbc/postgres/PostgresExampleEntityRepository.java
  data-r2dbc/src/test/java/io/micronaut/data/r2dbc/sqlserver/MSExampleEntityRepository.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/ExampleEntity.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/ExampleEntityRepository.java
Labels: type: bug

#3282 Fix parameter substitution for raw queries containing colon(s)
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/OracleXERepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/oraclexe/OracleXEFaceRepository.java
  data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/RawQueryMethodMatcher.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
Labels: type: bug

#3280 [data] Update common files for branch 4.11.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#3287 Fix issue with custom repository void methods
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/OracleXERepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/oraclexe/OracleXEFaceRepository.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java
Labels: type: bug

#3303 Added doc for Json View _metadata and optimistic locking
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/oraclexe/jsonview/OracleJdbcJsonViewSpec.groovy
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java
  data-processor/src/main/java/io/micronaut/data/processor/model/SourcePersistentEntity.java
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/JsonViewSpec.groovy
  data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/oraclexe/jsonview/OracleR2DbcJsonViewSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/Metadata.java
  data-tx/src/main/java/io/micronaut/transaction/annotation/Transactional.java
  src/main/docs/guide/dbc/sqlMapping/sqlJsonView.adoc
Labels: type: improvement, type: docs

#3305 Fix for runtime criteria containing multi level joins
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntityCommonAbstractCriteria.java
  data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityJoinSupport.java
  data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/AbstractSpecificationInterceptor.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/AuthorRepository.java
Labels: type: bug
