Repository micronaut-projects/micronaut-data, pull requests merged in 2025-06, with the labels that each got.

#3443 [data] Update common files for branch 4.13.x
  .github/workflows/release.yml
Labels: relates-to: build

#3446 Link text to Jakarta Data Specification
  src/main/docs/guide/shared/jakartaData.adoc
Labels: type: docs

#3445 Fix regression issues
  data-model/src/main/java/io/micronaut/data/model/CursoredPage.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractCursoredPageSpec.groovy
  gradle/libs.versions.toml
Labels: type: bug
