Repository micronaut-projects/micronaut-data, pull requests merged in 2025-07, with the labels that each got.

#3468 Fix pageable regression issue
  data-azure-cosmos/src/main/java/io/micronaut/data/cosmos/operations/DefaultReactiveCosmosRepositoryOperations.java
  data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultPreparedQuery.java
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractPageSpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/repositories/BookRepository.java
Labels: type: bug

#3481 Revert logic for loading many-to-one and one-to-one
  data-azure-cosmos/build.gradle
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/many2one/MultiManyToOneJoinSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/one2many/OneToManyHierarchicalSpec.groovy
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/h2/remap/StudentRepository.java
  data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresRepositorySpec.groovy
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2DocumentRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/h2/H2DocumentTypeRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/mysql/MySqlCatalogRepository.java
  data-jdbc/src/test/java/io/micronaut/data/jdbc/postgres/PostgresBookRepository.java
  data-model/src/main/java/io/micronaut/data/model/Association.java
  data-model/src/main/java/io/micronaut/data/model/PersistentEntityUtils.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java
  data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java
  data-model/src/main/java/io/micronaut/data/model/runtime/RuntimeAssociation.java
  data-processor/src/test/groovy/io/micronaut/data/model/jpa/criteria/CriteriaSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildDeleteSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildQuerySpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildUpdateSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/FindSpec.groovy
  data-processor/src/test/groovy/io/micronaut/data/processor/visitors/RelationshipSpec.groovy
  data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java
  data-runtime/src/test/groovy/io/micronaut/data/runtime/criteria/CriteriaSpec.groovy
  data-runtime/src/test/groovy/io/micronaut/data/runtime/criteria/StaticCriteriaSpec.groovy
  data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy
  data-tck/src/main/java/io/micronaut/data/tck/entities/Document.java
  data-tck/src/main/java/io/micronaut/data/tck/entities/DocumentType.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/BookRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/DocumentRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/DocumentTypeRepository.java
  data-tck/src/main/java/io/micronaut/data/tck/repositories/SaleItemRepository.java
  doc-examples/jdbc-example-java/src/test/java/example/StaticMetamodelTest.java
  gradle/libs.versions.toml
Labels: type: regression

#3496 doc: fix Jakarta Data artifact Id
  src/main/docs/guide/shared/jakartaData.adoc
Labels: type: docs
